local M = {}

function M.setup()
	require("onedarkpro").setup({
		colors = {
			-- Match the classic one-dark/onedark.nvim palette while keeping onedarkpro active.
			onedark = {
				black = "#181a1f",
				comment = "#5c6370",
				cursorline = "#31353f",
				color_column = "#31353f",
				fold = "#393f4a",
				line_number = "#5c6370",
				indentline = "#3b3f4c",
				selection = "#3b3f4c",
				float_bg = "#21252b",
				bg_statusline = "#393f4a",
				fg_gutter = "#5c6370",
				diff_add = "#31392b",
				diff_delete = "#382b2c",
				diff_change = "#1c3448",
				diff_text = "#2c5372",
			},
		},
		highlights = {
			ColorColumn = { bg = { onedark = "#31353f" } },
			CursorLine = { bg = { onedark = "#31353f" } },
			LineNr = { fg = { onedark = "#5c6370" } },
			CursorLineNr = { fg = { onedark = "#abb2bf" } },
			Visual = { bg = { onedark = "#3b3f4c" } },
			Pmenu = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			PmenuSbar = { bg = { onedark = "#31353f" } },
			PmenuSel = { fg = { onedark = "#282c34" }, bg = { onedark = "#73b8f1" } },
			PmenuThumb = { bg = { onedark = "#5c6370" } },
			StatusLine = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#393f4a" } },
			StatusLineNC = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			NormalFloat = { bg = { onedark = "#21252b" } },
			FloatBorder = { fg = { onedark = "#5c6370" }, bg = { onedark = "#21252b" } },
			MasonBackdrop = { bg = { onedark = "#181a1f" } },
			MasonNormal = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
			MasonHeader = { fg = { onedark = "#282c34" }, bg = { onedark = "#e5c07b" }, bold = true },
			MasonHeaderSecondary = { fg = { onedark = "#282c34" }, bg = { onedark = "#56b6c2" }, bold = true },
			MasonHighlight = { fg = { onedark = "#56b6c2" } },
			MasonHighlightBlock = { fg = { onedark = "#282c34" }, bg = { onedark = "#56b6c2" } },
			MasonHighlightBlockBold = { fg = { onedark = "#282c34" }, bg = { onedark = "#56b6c2" }, bold = true },
			MasonHighlightSecondary = { fg = { onedark = "#e5c07b" } },
			MasonHighlightBlockSecondary = { fg = { onedark = "#282c34" }, bg = { onedark = "#e5c07b" } },
			MasonHighlightBlockBoldSecondary = {
				fg = { onedark = "#282c34" },
				bg = { onedark = "#e5c07b" },
				bold = true,
			},
			MasonMuted = { fg = { onedark = "#5c6370" } },
			MasonMutedBlock = { fg = { onedark = "#282c34" }, bg = { onedark = "#5c6370" } },
			MasonMutedBlockBold = { fg = { onedark = "#282c34" }, bg = { onedark = "#5c6370" }, bold = true },
			MasonError = { fg = { onedark = "#e06c75" } },
			MasonWarning = { fg = { onedark = "#e5c07b" } },
			MasonHeading = { fg = { onedark = "#abb2bf" }, bold = true },
			WinSeparator = { fg = { onedark = "#5c6370" }, bg = { onedark = "#282c34" } },
			FoldColumn = { fg = { onedark = "#5c6370" }, bg = { onedark = "#282c34" } },
			SignColumn = { bg = { onedark = "#282c34" } },
			NvimTreeNormal = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
			NvimTreeNormalNC = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
			TelescopeNormal = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
			TelescopeBorder = { fg = { onedark = "#5c6370" }, bg = { onedark = "#21252b" } },
			TelescopeSelection = { fg = { onedark = "#c678dd" }, bg = { onedark = "#31353f" } },
			TelescopeMultiSelection = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			TelescopePromptPrefix = { fg = { onedark = "#c678dd" } },
			DiffAdd = { bg = { onedark = "#31392b" } },
			DiffChange = { bg = { onedark = "#1c3448" } },
			DiffDelete = { bg = { onedark = "#382b2c" } },
			DiffText = { bg = { onedark = "#2c5372" } },
			NvimTreeBookmarkIcon = { fg = { onedark = "#61afef" } },
			NvimTreeClosedFolderIcon = { fg = { onedark = "#61afef" } },
			NvimTreeFolderIcon = { fg = { onedark = "#61afef" } },
			NvimTreeOpenedFolderIcon = { fg = { onedark = "#61afef" } },
			NvimTreeOpenedFolderName = { fg = { onedark = "#61afef" } },
			NvimTreeRootFolder = { fg = { onedark = "#61afef" } },
			NvimTreeOpenedFile = { fg = { onedark = "#abb2bf" } },
			NvimTreeGitDeletedIcon = { fg = { onedark = "#e06c75" } },
			NvimTreeGitDirtyIcon = { fg = { onedark = "#e5c07b" } },
			NvimTreeGitFileDeletedHL = { fg = { onedark = "#e06c75" } },
			NvimTreeGitFileDirtyHL = { fg = { onedark = "#e5c07b" } },
			NvimTreeGitFolderDeletedHL = { fg = { onedark = "#e06c75" } },
			NvimTreeGitFolderDirtyHL = { fg = { onedark = "#e5c07b" } },
			BufferCurrent = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			BufferCurrentIndex = { fg = { onedark = "#61afef" }, bg = { onedark = "#31353f" } },
			BufferCurrentNumber = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			BufferCurrentBtn = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			BufferCurrentIcon = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			BufferCurrentSign = { fg = { onedark = "#61afef" }, bg = { onedark = "#31353f" } },
			BufferCurrentSignRight = { fg = { onedark = "#31353f" }, bg = { onedark = "#31353f" } },
			BufferCurrentPin = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			BufferCurrentPinBtn = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			BufferCurrentMod = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferCurrentModBtn = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferCurrentADDED = { fg = { onedark = "#98c379" }, bg = { onedark = "#31353f" } },
			BufferCurrentCHANGED = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferCurrentDELETED = { fg = { onedark = "#e06c75" }, bg = { onedark = "#31353f" } },
			BufferCurrentERROR = { fg = { onedark = "#e06c75" }, bg = { onedark = "#31353f" } },
			BufferCurrentHINT = { fg = { onedark = "#56b6c2" }, bg = { onedark = "#31353f" } },
			BufferCurrentINFO = { fg = { onedark = "#61afef" }, bg = { onedark = "#31353f" } },
			BufferCurrentWARN = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrent = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentIndex = { fg = { onedark = "#61afef" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentNumber = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentBtn = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentIcon = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentSign = { fg = { onedark = "#61afef" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentSignRight = { fg = { onedark = "#31353f" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentPin = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentPinBtn = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentMod = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentModBtn = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentADDED = { fg = { onedark = "#98c379" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentCHANGED = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentDELETED = { fg = { onedark = "#e06c75" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentERROR = { fg = { onedark = "#e06c75" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentHINT = { fg = { onedark = "#56b6c2" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentINFO = { fg = { onedark = "#61afef" }, bg = { onedark = "#31353f" } },
			BufferDefaultCurrentWARN = { fg = { onedark = "#e5c07b" }, bg = { onedark = "#31353f" } },
			BufferTabpages = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#282c34" } },
			TabLineSel = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
		},
	})
end

return M
