return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "onedark",
    },
  },
  {
    "olimorris/onedarkpro.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      colors = {
        onedark = {
          black = "#181a1f",
          comment = "#5c6370",
          cursorline = "#31353f",
          color_column = "#31353f",
          fold = "#393f4a",
          line_number = "#5c6370",
          indentline = "#3b3f4c",
          selection = "#3b3f4c",
          float_bg = "#21252b",
          bg_statusline = "#393f4a",
          fg_gutter = "#5c6370",
          diff_add = "#31392b",
          diff_delete = "#382b2c",
          diff_change = "#1c3448",
          diff_text = "#2c5372",
        },
      },
      highlights = {
        ColorColumn = { bg = { onedark = "#31353f" } },
        CursorLine = { bg = { onedark = "#31353f" } },
        LineNr = { fg = { onedark = "#5c6370" } },
        CursorLineNr = { fg = { onedark = "#abb2bf" } },
        Visual = { bg = { onedark = "#3b3f4c" } },
        Pmenu = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#31353f" } },
        PmenuSbar = { bg = { onedark = "#31353f" } },
        PmenuSel = { fg = { onedark = "#282c34" }, bg = { onedark = "#73b8f1" } },
        PmenuThumb = { bg = { onedark = "#5c6370" } },
        StatusLine = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#393f4a" } },
        StatusLineNC = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
        NormalFloat = { bg = { onedark = "#21252b" } },
        FloatBorder = { fg = { onedark = "#5c6370" }, bg = { onedark = "#21252b" } },
        FloatingTermNormal = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
        FloatingTermBorder = { fg = { onedark = "#5c6370" }, bg = { onedark = "#21252b" } },
        CopilotSuggestion = { fg = { onedark = "#83a598" }, italic = true },
        CopilotAnnotation = { fg = { onedark = "#83a598" } },
        MasonBackdrop = { bg = { onedark = "#181a1f" } },
        MasonNormal = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
        MasonHeader = { fg = { onedark = "#282c34" }, bg = { onedark = "#e5c07b" }, bold = true },
        MasonHeaderSecondary = { fg = { onedark = "#282c34" }, bg = { onedark = "#56b6c2" }, bold = true },
        MasonHighlight = { fg = { onedark = "#56b6c2" } },
        MasonHighlightBlock = { fg = { onedark = "#282c34" }, bg = { onedark = "#56b6c2" } },
        MasonHighlightBlockBold = { fg = { onedark = "#282c34" }, bg = { onedark = "#56b6c2" }, bold = true },
        MasonHighlightSecondary = { fg = { onedark = "#e5c07b" } },
        MasonHighlightBlockSecondary = { fg = { onedark = "#282c34" }, bg = { onedark = "#e5c07b" } },
        MasonHighlightBlockBoldSecondary = {
          fg = { onedark = "#282c34" },
          bg = { onedark = "#e5c07b" },
          bold = true,
        },
        MasonMuted = { fg = { onedark = "#5c6370" } },
        MasonMutedBlock = { fg = { onedark = "#282c34" }, bg = { onedark = "#5c6370" } },
        MasonMutedBlockBold = { fg = { onedark = "#282c34" }, bg = { onedark = "#5c6370" }, bold = true },
        MasonError = { fg = { onedark = "#e06c75" } },
        MasonWarning = { fg = { onedark = "#e5c07b" } },
        MasonHeading = { fg = { onedark = "#abb2bf" }, bold = true },
        WinSeparator = { fg = { onedark = "#5c6370" }, bg = { onedark = "#282c34" } },
        FoldColumn = { fg = { onedark = "#5c6370" }, bg = { onedark = "#282c34" } },
        SignColumn = { bg = { onedark = "#282c34" } },
        TelescopeNormal = { fg = { onedark = "#abb2bf" }, bg = { onedark = "#21252b" } },
        TelescopeBorder = { fg = { onedark = "#5c6370" }, bg = { onedark = "#21252b" } },
        TelescopeSelection = { fg = { onedark = "#c678dd" }, bg = { onedark = "#31353f" } },
        TelescopeMultiSelection = { fg = { onedark = "#5c6370" }, bg = { onedark = "#31353f" } },
        TelescopePromptPrefix = { fg = { onedark = "#c678dd" } },
        DiffAdd = { bg = { onedark = "#31392b" } },
        DiffChange = { bg = { onedark = "#1c3448" } },
        DiffDelete = { bg = { onedark = "#382b2c" } },
        DiffText = { bg = { onedark = "#2c5372" } },
      },
    },
  },
}
